### ISSUE TITLE
[Easy] Update README.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#1]
Improve README.md file

**Comment by GreenJ84** [comment]
What improvements are you looking for? Style? Information added? Reflow/Redesign? Let me know!

**Comment by boradesanket13** [comment]
@GreenJ84 
- Redesign it!
- Add icon/button for website's live link
- Remove portfolio link
- Add links of contributing.md and code-of-conduct.md
- Add badges, if possible. 

Attach screenshots of changes while making pull request for easier and fast review.

**Comment by Vanshiii203** [comment]
> @GreenJ84
> 
> * Redesign it!
> * Add icon/button for website's live link
> * Remove portfolio link
> * Add links of contributing.md and code-of-conduct.md
> * Add badges, if possible.
> 
> Attach screenshots of changes while making pull request for easier and fast review.

@Sanket1308 I would like to work on this issue

**Comment by kalaSriSaiRaksha** [comment]
please assign me this issue

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀
