### ISSUE TITLE
Error in Flags

### ISSUE THREAD

**Issue by Yogeshlodhi** [boradesanket13/Blaze#102]
In some Random search of cities/countries, the website is showing some different Flags that do not match with the input and in some cases the flag is partially visible due to the background color effects(brussels in this image )

<img width="348" alt="flag" src="https://user-images.githubusercontent.com/95206051/206144750-e62272ec-e68b-4f55-a21d-f152d1a32c26.png">
<img width="279" alt="flag2" src="https://user-images.githubusercontent.com/95206051/206144762-2d5f774c-5151-4844-8793-ce0ad246ff01.png">

**Comment by Yogeshlodhi** [comment]
@boradesanket13  please add label as codepeak if this issue seems meaningful to you

**Comment by boradesanket13** [comment]
Added the label! Will award points for raising this issue. @Yogeshlodhi 
Do you want to work on it?

**Comment by Yogeshlodhi** [comment]
@boradesanket13 
No sorry, I can not work on this issue.

**Comment by Dibyendu303** [comment]
I want to work on it @boradesanket13

**Comment by Dibyendu303** [comment]
@boradesanket13 Submitted a PR #106 . Please check.

**Comment by Abhijeet-2003** [comment]
If this issue is still open, I would like to work on it. @boradesanket13
