### ISSUE TITLE
Weather Card Content

### ISSUE THREAD

**Issue by Yogeshlodhi** [boradesanket13/Blaze#103]
The content in the weather card can be aligned in a better way they all are not in the same line.. And also the indication for the sky humidity is not in the same line as the text next to it which is not looking great at the moment.
<img width="351" alt="ss" src="https://user-images.githubusercontent.com/95206051/206146031-ddde5d90-39f9-4b63-80c8-b100c55610f6.png">

**Comment by Yogeshlodhi** [comment]
@boradesanket13 please add label as codepeak if this issue seems meaningful to you

**Comment by SusannaJoseph49** [comment]
can i have it assigned?

**Comment by boradesanket13** [comment]
Added the label! Will award points for raising this issue. @Yogeshlodhi
Do you want to work on it?

**Comment by boradesanket13** [comment]
@SusannaJoseph49 Go ahead!

**Comment by Yogeshlodhi** [comment]
> 

Yes I want to work on this
@boradesanket13 Kindly assign this to me

**Comment by Yogeshlodhi** [comment]
Yes I want to work on this, Please assign this issue to me, I might be able
to work on it in a better way since I've created the issue and know the
better idea

**Comment by boradesanket13** [comment]
@Yogeshlodhi  Any update! Feel free to ask your doubts here

**Comment by Yogeshlodhi** [comment]
Will give you the update by next week due to some technical error at my side.
Thank you

**Comment by boradesanket13** [comment]
Works, take your time🚀

**Comment by boradesanket13** [comment]
Any update! Feel free to ask your doubts here. If you want we can assign this issue to someone else @Yogeshlodhi

**Comment by Yogeshlodhi** [comment]
Yes Please assign this to someone else

**Comment by AlexHRodrii** [comment]
Can I have it assigned??
