### ISSUE TITLE
Default background image

### ISSUE THREAD

**Issue by Dibyendu303** [boradesanket13/Blaze#104]
Some places do not have an image. So we can display a default background image in that case.

**Comment by Abhijeet-2003** [comment]
@boradesanket13 I want to work on this issue.

**Comment by SattyamSamania** [comment]
> Some places do not have an image. So we can display a default background image in that case.

Hey @Dibyendu303 I would like to work on this issue.Please assign

**Comment by Abhijeet-2003** [comment]
I've sent a pr #109 for this issue. Please review and merge.
