### ISSUE TITLE
Add Pull Request Template and Issue Template

### ISSUE THREAD

**Issue by theritikchoure** [boradesanket13/Blaze#115]
With issue and pull request templates, you can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

After you create an issue and pull request templates in your repository, contributors can use the templates to open issues or describe the proposed changes in their pull requests according to the repository's contributing guidelines.

Pull request templates - https://axolo.co/blog/p/part-3-github-pull-request-template

For more, you can refer this - https://github.com/devspace/awesome-github-templates

**Comment by oraliahdz** [comment]
This sounds like a great idea, I would like to help with this. Is this still open?

**Comment by KarthikAravindR** [comment]
https://github.com/boradesanket13/Blaze/pull/119 - PR raised @theritikchoure
