### ISSUE TITLE
Temperature must be seen upto 2 decimal

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#15]
- Temperature must be seen upto 2 decimal points only e.g. 35.50 <br>
![Screenshot (1086)](https://user-images.githubusercontent.com/79108273/193438892-707b4cce-144d-4e58-a7c6-fe134b057470.png)

**Comment by mahirjain01** [comment]
Can you assign this to me?

**Comment by vivek-dhiman** [comment]
@Sanket1308 I would like to work on it. Please assign this to me.
