### ISSUE TITLE
Add toggle button to switch from degree Celsius to degree Fahrenheit

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#16]

**Comment by LemonDrop847** [comment]
Can I work on this? @Sanket1308

**Comment by boradesanket13** [comment]
@GreenJ84 I have created a separate issue here. You can work on it.

**Comment by boradesanket13** [comment]
Go ahead! @LemonDrop847 Contribute well.🚀

**Comment by GreenJ84** [comment]
I have this already done this and added into my pull request for Title change as well. Already pending review and merge

**Comment by boradesanket13** [comment]
Merged! Bring toggle below temperature. Will look better. @GreenJ84

**Comment by GreenJ84** [comment]
Pull request submitted to fix issue!
