### ISSUE TITLE
Add a better error modal when a user enters invalid input

### ISSUE THREAD

**Issue by ampsteric** [boradesanket13/Blaze#19]
Currently, the website shows a generic and default error popup of the browser when a user enters invalid input.
Please assign me this issue as a part of hacktoberfest so that I can start working on this.
![image](https://user-images.githubusercontent.com/56419358/193440848-e95e3722-fe50-46be-924b-25247fc419a4.png)

**Comment by boradesanket13** [comment]
Go ahead! Attach screenshot while creating PR for faster review. Contribute well🚀
