### ISSUE TITLE
[Easy] Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#2]
Improve contributing.md file.

**Comment by trishitchar** [comment]
Can I work with this?

**Comment by boradesanket13** [comment]
Assigned to you! Add good documentation. Contribute well.🚀

**Comment by Kartikey353** [comment]
Assign this issue to me I can do this.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by ayushigeorge** [comment]
Can I contribute as well?

**Comment by boradesanket13** [comment]
Go ahead, @ayushigeorge! Contribute well🚀

**Comment by combatantash** [comment]
Is this issue open?
I would like to work on it.
