### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by Preet-Sojitra** [boradesanket13/Blaze#23]
Currently it is showing random images. We can change it to image of the place that user has entered in the input.
Like suppose user search for new york, the background image will show the image of new york, like that.

If this is good idea , then I would like to work on this.

**Comment by boradesanket13** [comment]
Go for it! Have added hacktoberfest labels and have assigned you. Contribute well.

**Comment by Preet-Sojitra** [comment]
Will work on this. Thank you
