### ISSUE TITLE
Add °F and °C signs on the toggle itself.

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#24]
- Now: °F and °C signs are besides the toggle button
![Screenshot (1088)](https://user-images.githubusercontent.com/79108273/193442153-b46f3b3d-1bb9-406b-b5aa-128bce25202d.png)

- Needed: °F and °C signs should be on it.
![Feature](https://user-images.githubusercontent.com/79108273/193442053-08532c44-b928-400d-93a0-9043bea50d7b.jpeg)

**Comment by 0xPranjl** [comment]
can you assign it to me?

**Comment by Rahul-Palahwat** [comment]
Hey @Sanket1308 i would like to work on it , can you assign this to me?

**Comment by boradesanket13** [comment]
Assigned! Contribute well🚀
