### ISSUE TITLE
Dark/Light Mode

### ISSUE THREAD

**Issue by shivansh12032004** [boradesanket13/Blaze#29]
We can add a button, which when clicked will change dark mode to light mode and vice versa.
If relevant, I would love to work on this.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by shivamnarkar47** [comment]
Hey @Sanket1308 , I would like to work on this. **Can you assigned it to me ?**

**Comment by boradesanket13** [comment]
Sure! Assigned.
