### ISSUE TITLE
Add appropriate favicon to site

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#3]
- You can use your own design.

**Comment by arthurmatthew** [comment]
Can I work on this?

**Comment by boradesanket13** [comment]
Go ahead. Contribute well.🚀

**Comment by Shravanikale** [comment]
Hey @Sanket1308!! i want to work on this issue can you please assign this to me.😇

**Comment by boradesanket13** [comment]
Hey @Shravanikale, share a sample design here! Will assign you if it will be better than existing one.

**Comment by Shravanikale** [comment]
![sample_favicon](https://user-images.githubusercontent.com/109503478/193443672-fcb745b9-5988-48ba-8c9a-2cbdcf058313.png)

**Comment by boradesanket13** [comment]
Great work, @Shravanikale! I have assigned you. Go for the PR.🚀

**Comment by Shravanikale** [comment]
#28 favicon added

**Comment by boradesanket13** [comment]
Great PR!
