### ISSUE TITLE
[Feature] To show weather of user's location first.

### ISSUE THREAD

**Issue by Freedisch** [boradesanket13/Blaze#30]
I think the app should be able to give weather details our position first by detecting it, before searching for other locations

**Comment by boradesanket13** [comment]
Great idea, indeed! Can you explain your approach for the same, @Freedisch!

**Comment by harshkrt** [comment]
@Freedisch there won't be any need of searching bar if we ask for location permission from user to show their location directly

**Comment by Freedisch** [comment]
@harshk-codes There is still a need of the searching bar bcs with it, he will be able to check the weather for other location

**Comment by harshkrt** [comment]
cool

**Comment by boradesanket13** [comment]
Yes, @Freedisch! You can start working on it.

**Comment by gsm005** [comment]
I have wrote a python code to map user location on a map. Should I PR it?

**Comment by gsm005** [comment]
I have wrote a python code which will show the user a graph of weather of his current area between a particular duration of time.
This is the output  where the three lines are max, min and avg temperature. Should I merge it @Sanket1308 ?
![2022-10-02](https://user-images.githubusercontent.com/112815450/193460782-8e7ed834-c5ef-40fe-9388-c57dae2ce0a3.png)

**Comment by boradesanket13** [comment]
Create a folder 'python' and add it @gsm005 
How can you implement it in this project?

**Comment by gsm005** [comment]
Actually I am new to  Development. And Currently have knowledge about Python and CPP only. 
So, maybe we can make this graph display on the website or app. I have no idea how to implement it in this project. I have knowledge about an open weather database. So I used it to find weather record of particular duration of user's location.

**Comment by boradesanket13** [comment]
No problem, @gsm005 !
Create a folder 'python' and add it. Also add sample screenshots of graphs.

**Comment by gsm005** [comment]
Done!

**Comment by Kartikey353** [comment]
Can We Add Air Quality index with Weather information ?

**Comment by yashB-2002** [comment]
I think we can ask for user preferred location and show the preferred location and if user does not enter something app can show him default location. I would like to work on it.

**Comment by boradesanket13** [comment]
> Can We Add Air Quality index with Weather information ?

Good idea. 🚀
Share your approach. How will you implement?

**Comment by boradesanket13** [comment]
> I think we can ask for user preferred location and show the preferred location and if user does not enter something app can show him default location. I would like to work on it.

Showing the current location weather first seems better.
