### ISSUE TITLE
Restrict decimal to 2 digits

### ISSUE THREAD

**Issue by uday03meh** [boradesanket13/Blaze#38]
Celsius to Fahrenheit conversion of temperature adds any number of digits after decimal which doesn't look good, we can use JavaScript to restrict it to 2 decimal places in Fahrenheit.

![image](https://user-images.githubusercontent.com/59679281/193477473-973afccc-c0ec-4fc4-ba06-004f5a37e780.png)

**Comment by yashB-2002** [comment]
Hey I would like to work on this issue please assign it to me.

**Comment by boradesanket13** [comment]
Hey @yashB-2002 🚀
It's already assigned. I'll assign you if he doesn't complete in 24 hours. Till then work on other issues.
Find more issues here:
https://github.com/Sanket1308/Weather-App/
https://github.com/Sanket1308/javascript-quote-generator
https://github.com/Sanket1308/website-authentication-process
https://github.com/Sanket1308/Simple-Calculator
https://github.com/Sanket1308/analog-clock
https://github.com/Sanket1308/bots-collection

**Comment by uday03meh** [comment]
I think someone made a PR which resolves this issue, original site is showing 2 digits after decimal. We can close this issue then.
