### ISSUE TITLE
Background image repeats when the image is too small for the screen

### ISSUE THREAD

**Issue by arthurmatthew** [boradesanket13/Blaze#4]
The background image repeats when the image is too small for the screen, which looks a little weird.
![Website Image](https://user-images.githubusercontent.com/89240346/193436268-4ca81ffc-a7c8-468e-90f8-f9227a7e1e51.png)
You can see to the right that the image repeats.

**Comment by arthurmatthew** [comment]
I can work on this, if that's okay.

**Comment by boradesanket13** [comment]
Go ahead! Attach screenshot of changes while making pull request for easier and fast review. Contribute well!🚀
