### ISSUE TITLE
[Easy] Hide Api Key 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [boradesanket13/Blaze#43]
Api key is visible to everyone . So i want to add an env file and store the key in that so that it is not visible to everyone . Can you assign it to me .

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by pranavajith** [comment]
I'd like to work on this issue, @boradesanket13 . Please assign it to me.

**Comment by boradesanket13** [comment]
🚀

**Comment by Abhijeet-2003** [comment]
I want to work on this issue. @boradesanket13

**Comment by Abhijeet-2003** [comment]
@boradesanket13 . Whatever I searched about this till now, it seems like adding the API key to an env file is possible only in a react or node application. Hence, it won't be feasible to do it for this one.

**Comment by Abhijeet-2003** [comment]
@boradesanket13 Please reply.

**Comment by boradesanket13** [comment]
@Abhijeet-2003 No problem! Will find an alternate way for the same! Closing this issue as of now.

**Comment by boradesanket13** [comment]
@Abhijeet-2003 No problem! Will find an alternate way for the same
