### ISSUE TITLE
Responsiveness and better placement of text and other divs

### ISSUE THREAD

**Issue by Bhavya-C-ai** [boradesanket13/Blaze#44]
I noticed how texts can get kind of merged if the screen size is reduced a little bit and how mist text is a little misaligned. 
I would like to work on this issue and can it be labelled hacktober-accepted too?

![image](https://user-images.githubusercontent.com/96719986/193704866-81fc4663-a5a3-49da-9543-5100bd156e18.png)

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by Bhavya-C-ai** [comment]
It's done. You check it in open PRs and let me know any feedback:)
