### ISSUE TITLE
Designing a logo 

### ISSUE THREAD

**Issue by Vanshiii203** [boradesanket13/Blaze#45]

**Comment by Vanshiii203** [comment]
hey @Sanket1308 I have designed this logo. Can please check it once?
![49029BCE-8D0A-4685-85AA-06FD63941B67-removebg-preview](https://user-images.githubusercontent.com/94471189/194033980-8f41c31f-c01d-4550-b1ca-0b8ed89e5d29.png)

**Comment by boradesanket13** [comment]
Great job! Create a PR.
