### ISSUE TITLE
Add temperature in  °F 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#5]
Currently temperature is shown in °C on site. You make changes to show it is both.

**Comment by ghost** [comment]
Can I work with this?

**Comment by GreenJ84** [comment]
Would love to work on getting ℉ implemented within the project!

**Comment by boradesanket13** [comment]
@GreenJ84 @trishit-char 
Have assign to you. Attach Screenshot of changes while making pull request for easier and fast review. Contribute well!🚀

**Comment by vivek-dhiman** [comment]
@Sanket1308 I too would like to work on it. Please assign this to me too.

**Comment by mahirjain01** [comment]
Can you please assign this to me?  I can help finish the process faster.
