### ISSUE TITLE
Enhancement and Fixes

### ISSUE THREAD

**Issue by incognion** [boradesanket13/Blaze#54]
#### Current issue
- After Every Search, user have to clear the search box first, then enter new city to search in search box.

#### To fix
- It would be better that after every search, search box get automatically cleared, so that if user want to search for another city, he will just enter new city name in search box and search.

#### Purpose
- Better User Experience.

**Comment by DhavalDobariya333** [comment]
Can I work with this?

**Comment by DhavalDobariya333** [comment]
I have done it and raised Pull request

**Comment by incognion** [comment]
@DhavalDobariya333 why are you so desperate man 😂

**Comment by DhavalDobariya333** [comment]
Sorry 😅 I am new 
please explain me 
if I am wrong and guide me

**Comment by incognion** [comment]
No worry, but have some patience. Exceptions aside It always better to first raise issue and get assigned, then work on that issue. Otherwise direct going for PR may spoil your hard work, it may get rejected.
Anyway, you've worked on this issue. So I'm not gonna do it. Let see if maintainer merge Your PR.
