### ISSUE TITLE
Temperature and other details are still visible after entering invalid place name.

### ISSUE THREAD

**Issue by ampsteric** [boradesanket13/Blaze#58]
I am opening this new issue after @Sanket1308 told me in #37 to resolve this issue and submit a new PR.

Please review the PR attached below and merge it.
Attaching a screenshot for faster review.
![image](https://user-images.githubusercontent.com/56419358/194597068-92ca8883-b847-4b89-abef-f4169eb9cc51.png)

**Comment by boradesanket13** [comment]
Good, merged!
