### ISSUE TITLE
[Moderate] Add a better animation to the 'OK' button

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#62]
![Screenshot (1115)](https://user-images.githubusercontent.com/79108273/194743951-70dd7573-9b74-4e13-9935-b3c6e993c0bb.png)

**Comment by Vanshiii203** [comment]
@Sanket1308 I would like to work on this

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by Bhawna147** [comment]
@Sanket1308 can i work on this ?

**Comment by Vanshiii203** [comment]
> @Sanket1308 can i work on this ?

Hey bhawana 
I am working on this you can find some other issue

**Comment by boradesanket13** [comment]
@Bhawna147 , thanks for your interest!
We're assigning issues on a first come first serve basis. If @Vanshiii203 isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).
