### ISSUE TITLE
[Easy] Fix bug where nothing displays after entering a valid city name

### ISSUE THREAD

**Issue by cardosoIsaac** [boradesanket13/Blaze#66]
I submitted a pull request for another enhancement before raising an issue first. Sorry about that.
I would also like to fix the bug where nothing displays after entering an invalid city name and pressing the OK button. 
I would suggest doing a quick page reload after pressing OK. Can I work on this? Or do you have something else in mind to fix this?

<img width="1108" alt="NameNotFound" src="https://user-images.githubusercontent.com/39445826/194785053-a90d9606-2175-4bda-b792-7a6640215ba0.png">
<img width="1074" alt="NoInfoAfterward" src="https://user-images.githubusercontent.com/39445826/194785059-a807b445-0a78-44c1-bec2-76d3444c0379.png">

**Comment by cardosoIsaac** [comment]
Not sure if you add the labels or I need to. Sorry I'm kind of new to this.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by cardosoIsaac** [comment]
Done. Now the page reloads after clicking OK. Thank you.
