### ISSUE TITLE
[Easy] validation & errors

### ISSUE THREAD

**Issue by DhavalDobariya333** [boradesanket13/Blaze#69]
- validation in the empty input
- theme button console message clear 
- after gating error on city name it's not working correctly and getting any output

Please assign this to me, Thank You.

![Screenshot (1659)](https://user-images.githubusercontent.com/86626640/194928540-d8873d9d-5a89-4aeb-baf5-17908a499927.png)

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀
