### ISSUE TITLE
Add a default image if the images is not available in unsplash API

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#73]
![Screenshot (1123)](https://user-images.githubusercontent.com/79108273/195758544-7c4a11b7-7a28-4e6c-af91-242271314576.png)

**Comment by ThisisMS11** [comment]
Please assign this issue to me.

**Comment by boradesanket13** [comment]
@ThisisMS11 
Go ahead! Contribute well🚀

**Comment by ThisisMS11** [comment]
I have made a pull request regarding the same . Can you please check out and tell if it works for you or not.Thanks
