### ISSUE TITLE
Design improvement & cursor

### ISSUE THREAD

**Issue by DhavalDobariya333** [boradesanket13/Blaze#80]
- I want to some card design improvements as shown in the image.

![Screenshot](https://user-images.githubusercontent.com/86626640/196005719-47cb2118-3e01-4929-af8f-6828ae15680b.png)

- also want to put a custom cursor on the web page

**Comment by DhavalDobariya333** [comment]
and need suggestions for which type of font I put only in the time section so it makes differs from the weather

Please assign this to me, Thank You.

**Comment by boradesanket13** [comment]
Keep the font same just give and empty line before date.

**Comment by DhavalDobariya333** [comment]
Can I also change the mouse cursor? or only just card design.
