### ISSUE TITLE
Add a flag near the city name

### ISSUE THREAD

**Issue by UrijHoruzij** [boradesanket13/Blaze#82]
I want to make some improvements to the design as shown in the image.

![image](https://user-images.githubusercontent.com/63039080/197785264-b08eda5d-ac47-413b-8faa-f236f5bb60cc.png)

**Comment by boradesanket13** [comment]
Thanks for raising the issue. That's a good idea. You can work on it. Make sure
- Flag changes according to country
- Make the flag a little smaller

**Comment by UrijHoruzij** [comment]
I will take on this task. Previously, I checked the receipt of information about the country.

**Comment by boradesanket13** [comment]
Go ahead, @UrijHoruzij! Contribute well🚀
