### ISSUE TITLE
Update LEARN.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#85]
A LEARN.md file to provide step by step instructions, with text and/or media, on how to built this project from scratch.

**Comment by pruthviiiiii** [comment]
assign me plss

**Comment by 1ananya3** [comment]
I want to work on this issue. Please assign it to me.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by boradesanket13** [comment]
@1ananya3 Any update! Feel free to ask your doubts here
