### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#86]

**Comment by boradesanket13** [comment]
Add 
- portfolio
- badges
- gifs

**Comment by pruthviiiiii** [comment]
Can  work on this plss

**Comment by ghost** [comment]
Please assign this to me @boradesanket13

**Comment by boradesanket13** [comment]
@itz-deepak Go ahead!

**Comment by ghost** [comment]
@boradesanket13 what i have to add in portfolio, and there are already lots of badges present in read me

**Comment by boradesanket13** [comment]
sanketborade.me
Just add this

**Comment by ghost** [comment]
I didn't get what I have to change

**Comment by boradesanket13** [comment]
[https://sanketborade.me/](https://sanketborade.me/)
Add this link the 'Links' Section in readme.md. That will do.
@itz-deepak

**Comment by SattyamSamania** [comment]
@boradesanket13 can I work on this?

**Comment by akunumanarif** [comment]
Is the issue resolved?
