### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#96]
Improve contributing.md file.

**Comment by pranavajith** [comment]
Hey @boradesanket13 
Could you assign this issue to me? I'll work on it and make a PR on 5th...
If not possible, could you assign this to me tomorrow?

**Comment by pranavajith** [comment]
Also, the data seems to be outdated. It seem to be for Sanket1308/Weather-App instead of boradesanket/Blaze. All the screenshots also seem to be outdated. Can I change all of the above?
And if yes, could you recommend some ways to upload the screenshots? What site to use, if google drive is allowed, and more.

**Comment by boradesanket13** [comment]
Assigning you this! Just drag the image in the markdown code and GitHub will do the work for you!

**Comment by pranavajith** [comment]
Thanks, @boradesanket13 ! ✨
Will ask in case of any doubts!! Means a lot to get my first assignment!

**Comment by pranavajith** [comment]
@boradesanket13 
I'd really like to continue contributing in this project.. Could you share me your discord id so that we could keep in touch regularly?

**Comment by pranavajith** [comment]
@boradesanket13 
I think I may have solved both issues in the same PR.. 
Would that count as only one PR? Because that'd be a disadvantage for me... 
Anything that can be done? Perhaps after you accept it, I can submit another PR?

**Comment by boradesanket13** [comment]
You will get points for both fairly. 

> @boradesanket13 I think I may have solved both issues in the same PR.. Would that count as only one PR? Because that'd be a disadvantage for me... Anything that can be done? Perhaps after you accept it, I can submit another PR?

**Comment by boradesanket13** [comment]
> @boradesanket13 I'd really like to continue contributing in this project.. Could you share me your discord id so that we could keep in touch regularly?

@Sanket1350 Discord ID
I prefer github discussion over discord tho
