### ISSUE TITLE
Add map

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Blaze#97]
Showcase a map showing user location
That would be much more descriptive view of weather.

**Comment by shivamgupta2020** [comment]
I am interested in this. Please assign this task to me.

**Comment by Ajeetesh2003** [comment]
Hello, @boradesanket13 I am interested to contribute to this issue. Please assign this issue to me.
(I have also created a PR for my previous task)

**Comment by srilakshmiv123** [comment]
> Showcase a map showing user location That would be much more descriptive view of weather.

I'm interested to contribute this issue.

**Comment by Tushar98644** [comment]
i am interested to work on this issue ....

**Comment by boradesanket13** [comment]
@shivamgupta2020 Go ahead!

**Comment by boradesanket13** [comment]
We're assigning issues on a first come first serve basis. If @shivamgupta2020 isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another codepeak issue [here](https://github.com/boradesanket13?tab=repositories).

**Comment by Tushar98644** [comment]
> We're assigning issues on a first come first serve basis. If @shivamgupta2020 isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another codepeak issue [here](https://github.com/boradesanket13?tab=repositories).

kindly assign me the issues on quotebuzz .....also created a pr for the same

**Comment by Ajeetesh2003** [comment]
@boradesanket13, how do you want me to add the map:
-Should I add it beside the weather information table on the main page or,
-Should I add it to a different page as the space available on the main webpage is less?

**Comment by boradesanket13** [comment]
@Ajeetesh2003 add it to a different page

**Comment by boradesanket13** [comment]
@Ajeetesh2003 Any update on this?
