### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by AyushTripathiIITP** [boradesanket13/Blaze#99]
I just checked your website and realized it did'nt had any favicon. **Can you assign me this issue**

**Comment by AyushTripathiIITP** [comment]
can u assign me this issue @boradesanket13

**Comment by ankushj0801** [comment]
I want to work on this issue. please assign it to me @boradesanket13

**Comment by boradesanket13** [comment]
@AyushTripathiIITP, 
Go ahead! Contribute well🚀

**Comment by boradesanket13** [comment]
We are assigning issues on FCFS basis. Find anothor issue. Happy contributing🚀 @ankushj0801

**Comment by AyushTripathiIITP** [comment]
![sun (1)](https://user-images.githubusercontent.com/101452500/206185650-a1eb1fe8-c0a7-422d-b581-0852d0539780.png)
check this image for favicon
![sun](https://user-images.githubusercontent.com/101452500/206185809-a7affa48-71c8-4178-a4e5-837a628ce79a.png)
or this image for favicon
@boradesanket13

**Comment by boradesanket13** [comment]
Go with 2nd
